DDHotKeyUtilities.h: Fix `undeclared identifier` modifier mask errors
Fix the following errors by importing Cocoa instead of Foundation:

    $ clang -x objective-c \
        -w \
        -framework Carbon \
        -framework Cocoa \
        -framework Foundation \
        -fobjc-arc \
        -c \
        DDHotKeyUtilities.m
    DDHotKeyUtilities.m:76:21: error: use of undeclared identifier 'NSControlKeyMask'
        if (modifiers & NSControlKeyMask) {
                        ^
    DDHotKeyUtilities.m:79:21: error: use of undeclared identifier 'NSAlternateKeyMask'
        if (modifiers & NSAlternateKeyMask) {
                        ^
    DDHotKeyUtilities.m:82:21: error: use of undeclared identifier 'NSShiftKeyMask'
        if (modifiers & NSShiftKeyMask) {
                        ^
    DDHotKeyUtilities.m:85:21: error: use of undeclared identifier 'NSCommandKeyMask'
        if (modifiers & NSCommandKeyMask) {
                        ^
    DDHotKeyUtilities.m:138:18: error: use of undeclared identifier 'NSControlKeyMask'
        if ((flags & NSControlKeyMask) > 0) { newFlags |= controlKey; }
                     ^
    DDHotKeyUtilities.m:139:18: error: use of undeclared identifier 'NSCommandKeyMask'
        if ((flags & NSCommandKeyMask) > 0) { newFlags |= cmdKey; }
                     ^
    DDHotKeyUtilities.m:140:18: error: use of undeclared identifier 'NSShiftKeyMask'
        if ((flags & NSShiftKeyMask) > 0) { newFlags |= shiftKey; }
                     ^
    DDHotKeyUtilities.m:141:18: error: use of undeclared identifier 'NSAlternateKeyMask'
        if ((flags & NSAlternateKeyMask) > 0) { newFlags |= optionKey; }
                     ^
    DDHotKeyUtilities.m:142:18: error: use of undeclared identifier 'NSAlphaShiftKeyMask'
        if ((flags & NSAlphaShiftKeyMask) > 0) { newFlags |= alphaLock; }
                     ^
    9 errors generated.